apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: kristian-app
spec:
  # kro uses this simple schema to create your CRD schema and apply it
  # The schema defines what users can provide when they instantiate the RGD (create an instance).
  schema:
    apiVersion: v1alpha1
    kind: KristianApp
    # Define custom types used in the spec.    
    # types:
      # Probe:
      #   httpGet:
      #     path: string
      #     port: integer
      #   initialDelaySeconds: integer
      #   periodSeconds: integer
      #   timeoutSeconds: integer
      #   successThreshold: integer
      #   failureThreshold: integer
    spec:
      # Spec fields that users can provide.
      name: string
      environment: string
      team: string
      product: string
      image:
        repo: string
        tag: string
        port: integer | default=8080
      ingress:
        enabled: boolean | default=false
        public: boolean | default=false
        path: string | default="/" 
        pathType: string | default="Prefix" enum="ImplementationSpecific,Exact,Prefix"
        servicePort: integer | default=8080
      resources:
        memory: string | default="256Mi"
        cpu: string | default="100m"
        memoryLimitOverride: string | default=""
      autoscaling:
        enabled: boolean | default=true
        minReplicas: integer | default=1 minimum=1
        maxReplicas: integer | default=3 minimum=2 maximum=10
        targetCPUUtilizationPercentage: integer | default=80
      # probes:
      #   enableStartupProbe: boolean | default=true
      #   enableReadinessProbe: boolean | default=false
      #   enableLivenessProbe: boolean | default=true
      #   startupProbeConfig: Probe | default={httpGet:{path:"/health", port:8080}, initialDelaySeconds:5, periodSeconds:10, timeoutSeconds:5, successThreshold:1, failureThreshold:3}
      #   readinessProbeConfig: Probe | default={httpGet:{path:"/health", port:8080}, initialDelaySeconds:10, periodSeconds:10, timeoutSeconds:5, successThreshold:1, failureThreshold:5}
      #   livenessProbeConfig: Probe | default={httpGet:{path:"/health", port:8080}, initialDelaySeconds:5, periodSeconds:15, timeoutSeconds:10, successThreshold:1, failureThreshold:3}
      serviceAccount:
        create: boolean | default=true
        name: string | default=""
      podDisruptionBudget:
        enabled: boolean | default=true
        minAvailable: integer | default=1
    # status:
      # Fields the controller will inject into instances status.
      # deploymentConditions: ${deployment.status.conditions}
      # availableReplicas: ${deployment.status.availableReplicas}

  # Define the resources this API will manage.
  resources:
    - id: deployment
      template:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: ${schema.spec.name}
          ownerReferences:
            - apiVersion: kro.run/v1alpha1
              kind: ${schema.kind}
              name: ${schema.metadata.name}
              uid: ${schema.metadata.uid}
              blockOwnerDeletion: true
              controller: false
          annotations:
            argocd.argoproj.io/tracking-id: ${schema.metadata.?annotations["argocd.argoproj.io/tracking-id"].orValue("")}
        spec:
          replicas: ${schema.spec.autoscaling.minReplicas}
          revisionHistoryLimit: 3
          strategy:
            type: RollingUpdate
            rollingUpdate:
              maxSurge: 1
              maxUnavailable: 0
          selector:
            matchLabels:
              app: ${schema.spec.name}
          template:
            metadata:
              labels:
                app: ${schema.spec.name}
            spec:
              serviceAccountName: "${ schema.spec.serviceAccount.name != '' ? schema.spec.serviceAccount.name : schema.spec.name + '-sa' }"
              securityContext:
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
              containers:
                - name: ${schema.spec.name}
                  image: ${schema.spec.image.repo}:${schema.spec.image.tag}
                  imagePullPolicy: IfNotPresent
                  lifecycle:
                    # Graceful shutdown: wait 5 seconds before terminating the container
                    preStop:
                      # Can be updated in 1.34 of kubernetes to sleep directly
                      exec:
                        command: ["/bin/sh", "-c", "sleep 5"]
                  ports:
                    - name: http
                      containerPort: ${schema.spec.image.port}
                      protocol: TCP
                  env:
                    - name: HOST_IP
                      valueFrom:
                        fieldRef:
                          fieldPath: status.hostIP
                  resources:
                    limits:
                      memory: ${schema.spec.resources.memory}
                    requests:
                      memory: "${ schema.spec.resources.memoryLimitOverride != '' ? schema.spec.resources.memoryLimitOverride : schema.spec.resources.memory }"
                      cpu: ${schema.spec.resources.cpu}
                  securityContext:
                    allowPrivilegeEscalation: false
                    readOnlyRootFilesystem: true
                    runAsNonRoot: true
                    runAsUser: 1000
                    capabilities:
                      drop:
                        - ALL
                  # livenessProbe: '${ schema.spec.probes.enableLivenessProbe ? schema.spec.probes.livenessProbeConfig : {} }'
                  # readinessProbe: '${ schema.spec.probes.enableReadinessProbe ? schema.spec.probes.readinessProbeConfig : {} }'
                  # startupProbe: '${ schema.spec.probes.enableStartupProbe ? schema.spec.probes.startupProbeConfig : {} }'
    - id: service
      template:
        apiVersion: v1
        kind: Service
        metadata:
          name: ${schema.spec.name}
          ownerReferences:
            - apiVersion: kro.run/v1alpha1
              kind: ${schema.kind}
              name: ${schema.metadata.name}
              uid: ${schema.metadata.uid}
              blockOwnerDeletion: true
              controller: false
          annotations:
            argocd.argoproj.io/tracking-id: ${schema.metadata.?annotations["argocd.argoproj.io/tracking-id"].orValue("")}
        spec:
          type: ClusterIP
          selector: ${deployment.spec.selector.matchLabels} # Use the deployment selector
          ports:
            - name: http
              protocol: TCP
              port: ${schema.spec.image.port}
              targetPort: http

    - id: ingress
      includeWhen:
        - ${schema.spec.ingress.enabled}
      template:
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: ${schema.spec.name}
          ownerReferences:
            - apiVersion: kro.run/v1alpha1
              kind: ${schema.kind}
              name: ${schema.metadata.name}
              uid: ${schema.metadata.uid}
              blockOwnerDeletion: true
              controller: false
          annotations:
            argocd.argoproj.io/tracking-id: ${schema.metadata.?annotations["argocd.argoproj.io/tracking-id"].orValue("")}
        spec:
          ingressClassName: '${ schema.spec.ingress.public ? "traefik" : "traefik-internal" }'
          rules:
            - http:
                paths:
                  - path: ${schema.spec.ingress.path}
                    pathType: ${schema.spec.ingress.pathType}
                    backend:
                      service:
                        name: ${service.metadata.name} # Use the service name
                        port:
                          number: ${schema.spec.ingress.servicePort}

    - id: serviceAccount
      includeWhen:
        - ${schema.spec.serviceAccount.create}
      template:
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: "${ schema.spec.serviceAccount.name != '' ? schema.spec.serviceAccount.name : schema.spec.name + '-sa' }"
          ownerReferences:
            - apiVersion: kro.run/v1alpha1
              kind: ${schema.kind}
              name: ${schema.metadata.name}
              uid: ${schema.metadata.uid}
              blockOwnerDeletion: true
              controller: false
          annotations:
            argocd.argoproj.io/tracking-id: ${schema.metadata.?annotations["argocd.argoproj.io/tracking-id"].orValue("")}

    - id: podDisruptionBudget
      includeWhen:
        - ${schema.spec.podDisruptionBudget.enabled}
        - ${schema.spec.podDisruptionBudget.minAvailable > 0}
      template:
        apiVersion: policy/v1
        kind: PodDisruptionBudget
        metadata:
          name: ${schema.spec.name}
          ownerReferences:
            - apiVersion: kro.run/v1alpha1
              kind: ${schema.kind}
              name: ${schema.metadata.name}
              uid: ${schema.metadata.uid}
              blockOwnerDeletion: true
              controller: false
          annotations:
            argocd.argoproj.io/tracking-id: ${schema.metadata.?annotations["argocd.argoproj.io/tracking-id"].orValue("")}
        spec:
          minAvailable: ${schema.spec.podDisruptionBudget.minAvailable}
          selector:
            matchLabels:
              app: ${schema.spec.name}